### ISSUE TITLE
Timeout/write error on Termux

### ISSUE THREAD

**Issue by alexmozaidze** [ofirgall/open.nvim#7]
For one `termux-open-url` takes some time to execute, giving me this error:
![Screenshot_2023-05-04-03-55-12-648-edit_com termux](https://user-images.githubusercontent.com/51371527/236075631-f5f68135-b9fd-4652-a559-d90020aec89a.jpg)

Second thing, `termux-open-url` only accepts valid url's, so the address must be prepended with the protocol (see https://github.com/termux/termux-app/issues/1684), so be wary of that in case you'd want to implement #3.

**Comment by ofirgall** [comment]
Hey, I'm not familiar with `termux-open-url` but the errors seems to occur because of time out of curl to `https://api.github.com/repos/ofirgall/open.nvim`.
Can you try to re-run the curl command that appears in the error message in your terminal?

**Comment by alexmozaidze** [comment]
I ran `curl -sSL -D ./bruh-zone --compressed -X GET https://api.github.com/repos/ofirgall/open.nvim` and it worked. This is most definitely a timeout problem.

**Comment by ofirgall** [comment]
I don't know what is the problem but you should open a ticket in [plenary.nvim](nvim-lua/plenary.nvim) because it says it timed out in the image you attached.

**Comment by alexmozaidze** [comment]
I found [this issue](https://github.com/nvim-lua/plenary.nvim/issues/231) on plenary.nvim, perhaps, this could be fixed by setting the timeout on open.nvim's side?

**Comment by ofirgall** [comment]
Feel free to add timeout in `curl_opts` at open.nvim's setup

**Comment by alexmozaidze** [comment]
I put the timeout to 10 minutes (just to be sure) and discovered a different error message:
![Screenshot_2023-05-05-20-06-58-456_com termux](https://user-images.githubusercontent.com/51371527/236510317-5a90b442-3a05-4a02-aa6c-4dc3075b3bf0.png)

**Comment by alexmozaidze** [comment]
This really seems like an issue on plenary's side. I'll open an issue there later.

**Comment by alexmozaidze** [comment]
Solved with merging https://github.com/nvim-lua/plenary.nvim/pull/503. In order to make open.nvim work on Termux, one must set `XDG_RUNTIME_DIR` like so:
```sh
# .bashrc
export XDG_RUNTIME_DIR="$PREFIX/tmp"
```

Can you, please, mention this in the README?

**Comment by ofirgall** [comment]
Thanks!
